import Head from 'next/head';
import LogoWLC from '../../images/logo.svg'

const Seo = () => {
  return (
    <Head>
      <title>WLC Alevinos</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Seo;
